[project]
org-name= "wso2"
version= "0.1.0"
authors = ["WSO2"]
keywords = ["ballerina", "salesforce", "sfdc", "client", "connector"]
repository = "https://github.com/wso2-ballerina/module-salesforce"
